### Variáveis
@url = http://localhost:3000

## POST
POST {{url}}/links
Content-Type: application/json

{
"urlNormal": "https://moodle.utfpr.edu.br/mod/assign/view.php?id=1968820",
"legendaLink": "JOGADOR FAMOSO DE VOLEIBOL QUE JOGA COM A 9"
}